stages:
  - build
  - deploy

build-image:
  stage: build
  before_script:
    - docker compose dowm --rmi all
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/"
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN"
  script:
    - docker build -t admisi-service:dev ./ --no-cache
  only:
    - main

deploy-app:
  stage: deploy
  only:
    - main
  script:
    - docker compose up -d