services:
  adameds-admisi:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    container_name: api-adameds-admisi
    image: adameds/admisi-service:dev
    environment:
      SYNC_DB: ${SYNC_DB}
      APP_MODE: ${APP_MODE}
      APP_NAME: ${APP_NAME}
      WITH_SYNC_DB: ${WITH_SYNC_DB}
      DATAMASTER_SERVICE_URL: ${DATAMASTER_SERVICE_URL}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
    # volumes:
    #   - type: bind
    #     source: /home/engineer/adameds/.env.vault
    #     target: /adameds-admisi/.env.vault
    networks:
      - admisi
    ports:
      - 8083:8083
    restart: always
networks:
  admisi:
    driver: bridge
