version: '3.8'
services:
  adameds-admisi:
    container_name: admisi-service
    image: admisi-service:dev
    environment:
      APP_MODE: ${APP_MODE}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SYNC_DB: ${SYNC_DB}
    volumes:
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-admisi/public.key
      - type: bind
        source: /home/admin/adameds/private.key
        target: /adameds-admisi/private.key
    networks:
      - admisi
    ports:
      - 8083:8083
networks:
  admisi:
    driver: bridge